server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?serverTimezone=UTC
    username: root
    password: ch16334
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800800
      connection-timeout: 38000
      connection-test-query: SELECT 1



  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    databse: 0
#    password: root
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true




mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xxxx.server.pojo
  configuratioin:
    map-underscore-to-camel-case: false

logging:
  level:
    com.xxxx.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer

